- name: Update all Debian servers
  hosts: My_servers
  become: yes
  tasks:
    - name: Update the apt package index
      apt:
        update_cache: yes

    - name: Upgrade all apt packages to the latest version
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
